/**
 * strip-logo-bg.mjs
 * ─────────────────────────────────────────────────────────────
 * Removes semi-transparent background pixels from brand logo PNGs.
 *
 * The PNGs were generated by imagetracer.js which embeds low-opacity
 * background paths (~7% alpha) covering the full canvas. This script
 * sets every pixel whose alpha is below THRESHOLD to fully transparent.
 *
 * Uses only Node.js built-ins (fs + zlib). No npm dependencies.
 * Run: node scripts/strip-logo-bg.mjs
 * ─────────────────────────────────────────────────────────────
 */

import fs from 'fs';
import zlib from 'zlib';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

// Pixels with alpha strictly below this value are zeroed out.
// imagetracer background paths sit around alpha ~18 (≈7% of 255).
// Logo strokes are 44–100%+ opacity.
// 60 is a safe threshold — well above background noise, below any real stroke.
const THRESHOLD = 60;

const FILES = [
  path.join(ROOT, 'public', 'logo', 'brand-logo-dark.png'),
  path.join(ROOT, 'public', 'logo', 'brand-logo-light.png'),
];

// ─── CRC-32 ────────────────────────────────────────────────────────────────

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i++) crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ buf[i]) & 0xff];
  return (crc ^ 0xffffffff) >>> 0;
}

// ─── PNG chunk helpers ─────────────────────────────────────────────────────

function parseChunks(buf) {
  // Verify PNG signature
  const SIG = [137, 80, 78, 71, 13, 10, 26, 10];
  for (let i = 0; i < 8; i++) {
    if (buf[i] !== SIG[i]) throw new Error('Not a valid PNG file');
  }

  const chunks = [];
  let pos = 8;
  while (pos < buf.length) {
    const length = buf.readUInt32BE(pos);
    const type   = buf.slice(pos + 4, pos + 8).toString('ascii');
    const data   = buf.slice(pos + 8, pos + 8 + length);
    chunks.push({ type, data: Buffer.from(data) });
    pos += 12 + length;
  }
  return chunks;
}

function buildChunk(type, data) {
  const buf = Buffer.alloc(12 + data.length);
  buf.writeUInt32BE(data.length, 0);
  buf.write(type, 4, 4, 'ascii');
  data.copy(buf, 8);
  buf.writeUInt32BE(crc32(buf.slice(4, 8 + data.length)), 8 + data.length);
  return buf;
}

// ─── PNG filter reverse pass ────────────────────────────────────────────────

function paeth(a, b, c) {
  const p = a + b - c;
  const pa = Math.abs(p - a);
  const pb = Math.abs(p - b);
  const pc = Math.abs(p - c);
  if (pa <= pb && pa <= pc) return a;
  if (pb <= pc) return b;
  return c;
}

function unfilter(raw, width, height, bpp) {
  const stride = width * bpp;
  const pixels = Buffer.alloc(height * stride);

  for (let y = 0; y < height; y++) {
    const filterType = raw[y * (stride + 1)];
    const src = raw.slice(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    const dst = pixels.slice(y * stride, (y + 1) * stride);
    const prev = y > 0 ? pixels.slice((y - 1) * stride, y * stride) : Buffer.alloc(stride);

    for (let x = 0; x < stride; x++) {
      const left      = x >= bpp ? dst[x - bpp] : 0;
      const above     = prev[x];
      const upperLeft = x >= bpp ? prev[x - bpp] : 0;

      switch (filterType) {
        case 0: dst[x] = src[x]; break;
        case 1: dst[x] = (src[x] + left) & 0xff; break;
        case 2: dst[x] = (src[x] + above) & 0xff; break;
        case 3: dst[x] = (src[x] + Math.floor((left + above) / 2)) & 0xff; break;
        case 4: dst[x] = (src[x] + paeth(left, above, upperLeft)) & 0xff; break;
        default: throw new Error(`Unknown PNG filter type: ${filterType}`);
      }
    }
  }
  return pixels;
}

function refilterNone(pixels, width, height, bpp) {
  const stride = width * bpp;
  const out = Buffer.alloc(height * (stride + 1));
  for (let y = 0; y < height; y++) {
    out[y * (stride + 1)] = 0; // filter type: None
    pixels.copy(out, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }
  return out;
}

// ─── Main processor ────────────────────────────────────────────────────────

function stripBackground(filePath, alphaThreshold) {
  const src = fs.readFileSync(filePath);
  const chunks = parseChunks(src);

  // Read IHDR
  const ihdr = chunks.find(c => c.type === 'IHDR');
  if (!ihdr) throw new Error('Missing IHDR chunk');

  const width    = ihdr.data.readUInt32BE(0);
  const height   = ihdr.data.readUInt32BE(4);
  const bitDepth = ihdr.data[8];
  const colorType = ihdr.data[9];

  console.log(`  ${path.basename(filePath)}: ${width}×${height}, bit-depth=${bitDepth}, color-type=${colorType}`);

  if (bitDepth !== 8) throw new Error(`Unsupported bit depth: ${bitDepth} (only 8-bit supported)`);
  if (ihdr.data[12] !== 0) throw new Error('Interlaced PNGs not supported');

  let bpp;
  if (colorType === 6) {
    bpp = 4; // RGBA
  } else if (colorType === 2) {
    // RGB — no alpha channel; nothing to strip
    console.log('  → RGB (no alpha channel) — adding alpha channel');
    bpp = 3;
  } else {
    throw new Error(`Unsupported color type: ${colorType}`);
  }

  // Merge all IDAT chunks
  const idatData = Buffer.concat(chunks.filter(c => c.type === 'IDAT').map(c => c.data));
  const raw = zlib.inflateSync(idatData);

  if (colorType === 2) {
    // Convert RGB to RGBA, mark all pixels as fully opaque, no background to strip
    // (These files should not have a background problem if they're pure RGB)
    console.log('  → No background pixels to strip in RGB PNG.');
    return;
  }

  // Reverse filter → raw pixels
  const pixels = unfilter(raw, width, height, bpp);

  // Zero out pixels below threshold
  let stripped = 0;
  for (let i = 0; i < pixels.length; i += 4) {
    if (pixels[i + 3] < alphaThreshold) {
      pixels[i] = pixels[i + 1] = pixels[i + 2] = pixels[i + 3] = 0;
      stripped++;
    }
  }
  console.log(`  → Stripped ${stripped.toLocaleString()} background pixels (alpha < ${alphaThreshold})`);

  // Re-filter (None) + recompress
  const filtered    = refilterNone(pixels, width, height, bpp);
  const compressed  = zlib.deflateSync(filtered, { level: 9 });

  // Rebuild PNG — keep all chunks except old IDAT(s)
  const PNG_SIG = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  const outParts = [PNG_SIG];

  for (const chunk of chunks) {
    if (chunk.type === 'IDAT') continue; // drop old compressed data

    if (chunk.type === 'IEND') {
      // Insert new single IDAT before IEND
      outParts.push(buildChunk('IDAT', compressed));
    }
    outParts.push(buildChunk(chunk.type, chunk.data));
  }

  const out = Buffer.concat(outParts);
  fs.writeFileSync(filePath, out);
  console.log(`  ✓ Saved (${(out.length / 1024).toFixed(1)} KB)\n`);
}

// ─── Run ───────────────────────────────────────────────────────────────────

console.log(`\nStripping background pixels (alpha < ${THRESHOLD}) from logo PNGs…\n`);

for (const file of FILES) {
  if (!fs.existsSync(file)) {
    console.warn(`  ⚠ File not found: ${file}\n`);
    continue;
  }
  try {
    stripBackground(file, THRESHOLD);
  } catch (err) {
    console.error(`  ✗ Failed: ${err.message}\n`);
  }
}

console.log('Done.');
